#!/bin/sh
####  PBS preamble

#PBS -N Exam1_Cheng
#PBS -V

# Change the number of cores (ppn=4), amount of memory, and walltime
# based on what your job will require:
#PBS -l nodes=1:ppn=4,pmem=8gb,walltime=10:00:00

#PBS -A eeb416f17_flux
#PBS -q flux
#PBS -l qos=flux

#PBS -m abe
#PBS -j oe

####  End PBS preamble

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_JOBID" ]; then echo -n "Running on nodes/cores: "; qstat -n $PBS_JOBID | tail -1; fi

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi; echo -n "Current working directory: "; pwd
echo

#  Echo job script commands as they are executed

#  Set your max threads here
export OMP_NUM_THREADS=${PBS_NUM_PPN:-1}

#  Put your job script commands here:

####New gene expression mapping workflow

#Index transcriptome and align reads
bwa index -a is Sample_reference_transcriptome.fa > bwa_index.stdout 2> bwa_index.stderr
bwa aln -t4 Sample_reference_transcriptome.fa Sample_read1.fq > Sample_R1.sai 2> Sample_R1_bwa_aln.stderr
bwa aln -t4 Sample_reference_transcriptome.fa Sample_read2.fq > Sample_R2.sai 2> Sample_R2_bwa_aln.stderr

#Produce sam alignment file
bwa sampe Sample_reference_transcriptome.fa Sample_R1.sai Sample_R2.sai Sample_read1.fq Sample_read2.fq > Sample.sam 2> Sample_sampe.stderr

#Return only primary mapped reads
samtools view -b Sample.sam > Sample.bam
samtools view -F 0x904 -f 0x40 -b Sample.bam > output.filter.bam


#Get read counts
samtools sort -@ 4 -m 8G output.filter.bam -o output.filter.sorted.bam
samtools index output.filter.sorted.bam 
samtools idxstats output.filter.sorted.bam > output.counts.txt
